version: '3.1'

services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    healthcheck:
      test: "/usr/bin/psql -U postgres --execute \"d\""
      interval: 3s
      timeout: 1s
      retries: 120
    networks: 
      - go-api-network

  api: 
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
    networks: 
      - go-api-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - go-api-network

networks:
  go-api-network:
    driver: bridge
